apiVersion: v1
kind: Pod
metadata:
  name: go-server
  labels:
    app: go-server
  annotations: 
    instrumentation.opentelemetry.io/inject-go: "true"
    instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/root/main"
spec:
  containers:
  - name: go-server
    image:  ghcr.io/keisukesakasai/k8snovice35-demo/go-server:latest
    ports:
    - containerPort: 8080
    imagePullPolicy: Always
    env:    
      - name: OTEL_SERVICE_NAME
        value: "go-server"
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"        
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: k8snovice35-demo
  labels:
    app.kubernetes.io/name: go-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: go-server
