apiVersion: v1
kind: Service
metadata:
  name: oteltui
  namespace: k8snovice35-demo
spec:
  selector:
    app: otel-tui
  ports:
    # - name: otlp-grpc
    #   protocol: TCP
    #   port: 4317
    #   targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-tui
  namespace: k8snovice35-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-tui
  template:
    metadata:
      labels:
        app: otel-tui
    spec:
      containers:
        - name: otel-tui
          image: ymtdzzz/otel-tui:latest
          stdin: true
          tty: true
          command: ["/otel-tui", "--enable-zipkin"]
          ports:
            # - containerPort: 4317
            - containerPort: 4318

