apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-auto-instrumentation
spec:
  exporter:
    endpoint: http://oteltui:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://oteltui:4318